apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: microsvcs
  labels:
    kargo.akuity.io/cred-type: image
  annotations:
    kargo.akuity.io/repo-url-pattern: "docker.io/*"
type: Opaque
stringData:
  username: ${DOCKERHUB_USERNAME}
  password: ${DOCKERHUB_PAT}
