apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: microsvcs
  labels:
    kargo.akuity.io/cred-type: git
  annotations:
    kargo.akuity.io/repo-url-pattern: "https://github.com/davidaparicio/*"
type: Opaque
stringData:
  repoURL: "https://github.com/*"
  repoURLIsRegex: "true"
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}