apiVersion: v1
kind: Secret
metadata:
  name: quay-creds
  namespace: microsvcs
  labels:
    kargo.akuity.io/cred-type: image
  annotations:
    kargo.akuity.io/repo-url-pattern: "quay.io/*"
type: Opaque
stringData:
  repoURL: "quay.io/*"
  repoURLIsRegex: "true"
  username: ${QUAY_USERNAME}
  password: ${QUAY_PAT}
