apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: red-development
  namespace: microsvcs
spec:
  subscriptions:
    warehouse: red
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/davidaparicio/microsvcs.git
        writeBranch: main
        kustomize:
          images:
            - image: docker.io/davidaparicio/red
              path: k8s/overlays/development/red
    argoCDAppUpdates:
      - appName: red-development
        appNamespace: argocd
