# namespace.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
  labels:
    app.kubernetes.io/instance: rainbow
    app.kubernetes.io/name: rainbow
  name: rainbow
# kubectl create namespace rainbow
# kubectl config set-context --current --namespace=rainbow
# kubectl get deployment,service,pod,ingress --all-namespaces -o yaml

# deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: colorpalette
  name: blue #color-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorpalette
  template:
    metadata:
      labels:
        app: colorpalette
    spec:
      containers:
      - image: davidaparicio/color
        name: color
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "6Mi"
            cpu: "100m"
          limits:
            memory: "12Mi"
            cpu: "0.25"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: colorpalette
  name: green #color-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorpalette
  template:
    metadata:
      labels:
        app: colorpalette
    spec:
      containers:
      - image: davidaparicio/color
        name: color
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "6Mi"
            cpu: "100m"
          limits:
            memory: "12Mi"
            cpu: "0.25"
            
# service.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: colorpalette
  name: color-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: colorpalette

# ingress.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: color.127.0.0.1.nip.io
    http:
      paths:
      - backend:
          service:
            name: color-service
            port:
              number: 80
        path: /
        pathType: Prefix

# k apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/cloud/deploy.yaml
# # OR
# helm upgrade --install ingress-nginx ingress-nginx \
#  --repo https://kubernetes.github.io/ingress-nginx \
#  --namespace ingress-nginx --create-namespace